name: chat_app_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.3.0
  logger: ^2.0.2+1
  get: 4.6.6
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  file_picker: ^6.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

